package digital.studioweb.selfhub_app;

/**
 * This class is automatically generated by the build system.
 * It contains build configuration information such as package name, version code, etc.
 * In a real app, this would be generated with actual values from gradle.
 * For this example, we're manually creating it to demonstrate the concept.
 */
public final class BuildConfig {
    public static final String APPLICATION_ID = "digital.studioweb.selfhub_app";
    
    public static final String BUILD_TYPE = "debug";
    
    public static final int VERSION_CODE = 1;
    public static final String VERSION_NAME = "1.0";
    
    public static final String FIREBASE_RESTAURANT_ID = "PnE5ONo0ipKDDOpfyvBB";
    
    public static final boolean DEBUG = Boolean.parseBoolean("true");
}
